apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: differ
  name: differ
spec:
  type: ClusterIP
  ports:
  - name: headless
    port: 4567
    targetPort: 4567
  selector:
    io.kompose.service: differ
status:
  loadBalancer: {}
