apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: differ
  name: differ
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: differ
    spec:
      containers:
      - image: cyberdojo/differ
        name: cyber-dojo-differ
        resources:
          limits:
            memory: "1073741824"
        volumeMounts:
        - mountPath: /tmp
          name: differ-tmpfs0
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: differ-tmpfs0
status: {}
