apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: prometheus
    spec:
      containers:
      - image: cyberdojo/prometheus
        name: cyber-dojo-prometheus
        resources: {}
      restartPolicy: Always
status: {}
