apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: runner-stateless
  name: runner-stateless
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: runner-stateless
    spec:
      containers:
      - name: cyber-dojo-runner-stateless
        image: cyberdojo/runner-stateless
        resources:
          limits:
            memory: "2147483648"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
        - mountPath: /tmp
          name: runner-stateless-tmpfs0
      restartPolicy: Always
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: runner-stateless-tmpfs0
        emptyDir:
          medium: Memory

status: {}
