apiVersion: v1
kind: Service
metadata:
  name: starter
spec:
  selector:
    io.kompose.service: starter
  type: ClusterIP
  ports:
  - name: starter-port
    port: 4527
    targetPort: 4527
status:
  loadBalancer: {}
