apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storer
  labels:
    io.kompose.service: storer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: storer
    spec:
      containers:
      - env:
        - name: CYBER_DOJO_KATAS_ROOT
          value: /usr/src/cyber-dojo
        image: cyberdojo/storer
        name: cyber-dojo-storer
        ports:
        - containerPort: 4577
        resources:
          limits:
            memory: "2147483648"
        volumeMounts:
        - mountPath: /usr/src/cyber-dojo
          name: storer-data
      restartPolicy: Always
      volumes:
      - name: storer-data
        persistentVolumeClaim:
          claimName: storer-data
      securityContext:
        fsGroup: 19661
status: {}
