apiVersion: v1
kind: Service
metadata:
  name: storer
spec:
  type: ClusterIP
  ports:
  - name: serviceport
    port: 4577
    targetPort: 4577
  selector:
    io.kompose.service: storer
status:
  loadBalancer: {}
