apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: storer-data
  name: storer-data
spec:
  storageClassName: "standard"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
