apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: zipper
  name: zipper
spec:
  type: ClusterIP
  ports:
  - name: zipper-port
    port: 4587
    targetPort: 4587
  selector:
    io.kompose.service: zipper
status:
  loadBalancer: {}
