apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zipper
  name: zipper
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: zipper
    spec:
      containers:
      - image: cyberdojo/zipper
        name: cyber-dojo-zipper
        resources:
          limits:
            memory: "52428800"
        volumeMounts:
        - mountPath: /tmp
          name: zipper-tmpfs0
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: zipper-tmpfs0
status: {}
