apiVersion: v1
kind: Service
metadata:
  name: {{ template "cyber-dojo.fullname" . }}-nginx
  labels:
    app: {{ template "cyber-dojo.name" . }}
    chart: {{ template "cyber-dojo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.nginx.type }}
  ports:
    - port: {{ .Values.service.nginx.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "cyber-dojo.name" . }}
    release: {{ .Release.Name }}
